---
- name: Installer Java (prérequis Jenkins)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Ajouter clé Jenkins
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.gpg
    mode: '0644'

- name: Ajouter repository Jenkins
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Mettre à jour les dépôts
  apt:
    update_cache: yes

- name: Installer Jenkins
  apt:
    name: jenkins
    state: present

- name: Activer et démarrer Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started

